apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluent-bit
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: fluent-bit
        app.kubernetes.io/name: fluent-bit
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name }}
        - name: fluent-bit-parsers
          configMap:
            name: fluent-bit-parsers
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: etcmachineid
          hostPath:
            path: /etc/machine-id
            type: File
      containers:
        - name: fluent-bit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - '--workdir=/fluent-bit/etc'
            - '--config=/fluent-bit/etc/conf/fluent-bit.conf'
          ports:
            - name: http
              containerPort: 2020
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/conf
            - name: fluent-bit-parsers
              mountPath: /fluent-bit/etc/parsers.conf
              subPath: parsers.conf
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: etcmachineid
              readOnly: true
              mountPath: /etc/machine-id
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http

