apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: {{ .Values.serviceAccount.namespace }}  # Use the same namespace as your DaemonSet
data:
  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

