image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: "3.0.3"
  pullPolicy: IfNotPresent

serviceAccount:
  name: fluent-bit
  namespace: logging

service:
  type: ClusterIP
  port: 2020


configMap:
  name: fluent-bit
  fluentBitConf: |
    [SERVICE]
        Daemon Off
        Flush 5  # Send logs every 5 seconds instead of 1
        Log_Level info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name throttle
        Match kube.*
        Rate 500   # Allow max 500 logs per second
        Window 5   # Apply limit over 5 seconds
        Interval 1 # Evaluate every second

    [FILTER]
        Name grep
        Match kube.*
        Exclude log ^.*(kube-probe|liveness|readiness).*  # Drop unnecessary logs

    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch
        Port 9200
        Index fluent-bit
        Logstash_Format On
        Retry_Limit False
        Suppress_Type_Name On
